name: Deployment Pipeline

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  avoid_redundancy:
    runs-on: ubuntu-20.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

  lint: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
  
  build: 
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
      - name: Install dependencies
        run: npm ci
      - name: Build Project
        run: npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: integrations-example
          path: .next
        
  tests:
    needs: [lint, build]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20.11.0"
      - name: Install dependencies
        run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: integrations-example
          path: .next
      - name: Run Tests
        run: npm run test
      - name: Display Coverage
        uses: ArtiomTr/jest-coverage-report-action@v2

  # deploy:
  #   runs-on: ubuntu-20.04
  #   needs: [tests]
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

  #   steps:
  #     - name: Download artifact from build jobs
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: integrations-example
  #         path: .next
  #     - name: 'Deploy to Azure Web App'
  #       uses: azure/webapps-deploy@v2
  #       id: deploy-to-webapp
  #       with:
  #         app-name: 'integrations-example'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZURE_WEB_APP_PUBLISH_PROFILE }}
  #         package: .
          
    
    